# Generated by Django 4.2.21 on 2025-06-12 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_line', models.CharField(max_length=100)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('order_date', models.DateField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business_intelligence.customer'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='SalesFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField()),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_facts', to='business_intelligence.customerorder')),
                ('order_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_facts', to='business_intelligence.time')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_facts', to='business_intelligence.product')),
            ],
            options={
                'unique_together': {('order', 'product', 'order_date')},
            },
        ),
    ]
